---
abstract: 'DSL for database schema declaration'
author:
  - 'Masayuki Matsuki E<lt>y.songmu@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Schema-DSL
no_index:
  directory:
    - inc
provides:
  DBIx::Schema::DSL:
    file: lib/DBIx/Schema/DSL.pm
    version: 0.05
  DBIx::Schema::DSL::Context:
    file: lib/DBIx/Schema/DSL/Context.pm
    version: 0
requires:
  Array::Diff: 0
  Clone: 0.06
  Moo: 1.000003
  SQL::Translator: 0.11011
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
