---
abstract: 'DSL for Database schema declaration'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.2, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Schema-DSL
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  DBIx::Schema::DSL:
    file: lib/DBIx/Schema/DSL.pm
    version: 0.09
  DBIx::Schema::DSL::Context:
    file: lib/DBIx/Schema/DSL/Context.pm
requires:
  Array::Diff: 0
  Clone: 0.06
  Moo: 1.000003
  SQL::Translator: 0.11011
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-DBIx-Schema-DSL/issues
  homepage: https://github.com/Songmu/p5-DBIx-Schema-DSL
  repository: git://github.com/Songmu/p5-DBIx-Schema-DSL.git
version: 0.09
x_contributors:
  - 'tokubass <tomi21110@gmail.com>'
